name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Get tip commit
        id: tip
        run: |
          commit=$(gh api repos/golang/go/commits/master --jq '.sha')
          echo "commit=$commit" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Cache gotip
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/sdk/gotip
          key: ${{ runner.os }}-gotip-${{ steps.tip.outputs.commit }}
          restore-keys: |
            ${{ runner.os }}-gotip-
      - name: Install gotip
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
      - name: Run test
        run: GOEXPERIMENT=rangefunc gotip test -v ./...
