name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: install gotip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
      - name: test
        run: gotip test -v ./...
