name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Get tip commit
        id: tip
        run: |
          mkdir -p $HOME/sdk/gotip
          cd $HOME/sdk/gotip
          git clone --origin=origin --depth=1 https://go.googlesource.com/go .
          commit=$(git rev-parse origin/master)
          echo "commit=$commit" >> $GITHUB_OUTPUT
      - name: Cache gotip
        uses: actions/cache@v3
        with:
          path: $HOME/sdk/gotip
          key: ${{ runner.os }}-gotip-${{ steps.tip.outputs.commit }}
          restore-keys: |
            ${{ runner.os }}-gotip-
      - name: Install gotip
        run: |
          go install golang.org/dl/gotip@latest
          gotip download
      - name: Run test
        run: GOEXPERIMENT=rangefunc gotip test -v ./...
